# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'Just another developer'
tagline:             'Full stack development in details'
description:         'Full stack development in details: .NET, Azure, JavaScript, SQL, Design, performance.'
url:                 'https://fsou1.github.io/'
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              Maxim Zhukov
  email:             maxim.zhukov.dev@gmail.com

# For the social list
social_list:
  twitter:           https://twitter.com/maximzhukov_dev
  stackoverflow:     https://stackoverflow.com/users/2524304/maxim-zhukov
  github:            https://github.com/FSou1
  linkedin:          https://www.linkedin.com/in/maxim-zhukov-0648a8b5

# For the Jekyll SEO plugin https://github.com/jekyll/jekyll-seo-tag#usage
social:
  name: Maxim Zhukov
  links:
    - https://twitter.com/maximzhukov_dev
    - https://stackoverflow.com/users/2524304/maxim-zhukov
    - https://github.com/FSou1
    - https://www.linkedin.com/in/maxim-zhukov-0648a8b5

# For the Jekyll SEO plugin https://github.com/jekyll/jekyll-seo-tag#usage
twitter:
  username: maximzhukov_dev

# Custom vars
version:             1.0.0

exclude: [README.md, LICENSE.md]

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from